//! Automatic, non-invasive shell integration.
//!
//! Blocks are Tervin's headline feature and they need the shell to report prompt
//! boundaries. Asking every user to paste a line into their `.zshrc` first means
//! the product does not work when you open it, which is the wrong trade — so
//! Tervin injects the hook itself, **without modifying a single file the user
//! owns**.
//!
//! Each shell has one supported mechanism for this, and Tervin uses exactly that:
//!
//! | Shell | Mechanism |
//! |---|---|
//! | zsh | `ZDOTDIR` pointed at a generated directory whose rc files source the user's own, then the hook |
//! | bash | `--init-file` with a wrapper that sources the user's own rc, then the hook |
//! | fish | `XDG_DATA_DIRS` extended so fish finds the hook in `vendor_conf.d`, its documented extension point |
//! | PowerShell | `-NoExit -Command` after the profile has loaded |
//!
//! ## The rule that governs all of it
//!
//! **The user's configuration runs first, and runs unchanged.** Every generated
//! file sources the real one before adding anything, and `ZDOTDIR` is restored
//! afterwards so anything that re-reads it later sees the user's own value. If a
//! generated file were to fail, the shell would still be the user's shell.
//!
//! Injection is also declinable: `TERVIN_SHELL_INTEGRATION=0` disables the hook,
//! and [`InjectionMode::Off`] skips the mechanism entirely.

use crate::Shell;
use std::path::{Path, PathBuf};

/// How integration reaches a shell.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
#[derive(Default)]
pub enum InjectionMode {
    /// Inject automatically. Nothing the user owns is modified.
    #[default]
    Automatic,
    /// Do not inject. Blocks form only if the user sourced the hook themselves.
    Off,
}

/// What to add to a shell's launch so the hook loads.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Injection {
    /// Arguments inserted before the shell's own.
    pub args: Vec<String>,
    /// Environment to set. An empty value means "unset".
    pub env: Vec<(String, String)>,
    /// Why integration is unavailable, when it is. Shown rather than swallowed.
    pub unavailable: Option<String>,
}

impl Injection {
    fn unavailable(reason: impl Into<String>) -> Self {
        Self {
            unavailable: Some(reason.into()),
            ..Default::default()
        }
    }

    /// Whether the hook will load.
    pub fn is_active(&self) -> bool {
        self.unavailable.is_none() && (!self.args.is_empty() || !self.env.is_empty())
    }
}

/// Prepare integration for a shell, writing whatever files it needs.
///
/// `dir` is Tervin's own generated-script directory. Nothing outside it is
/// written.
pub fn prepare(shell: Shell, dir: &Path, mode: InjectionMode) -> Injection {
    if mode == InjectionMode::Off {
        return Injection::default();
    }

    let script = match crate::write_script(shell, dir) {
        Ok(path) => path,
        Err(e) => return Injection::unavailable(format!("Could not write the hook: {e}")),
    };

    match shell {
        Shell::Zsh => prepare_zsh(dir, &script),
        Shell::Bash => prepare_bash(dir, &script),
        Shell::Fish => prepare_fish(dir, shell),
        Shell::PowerShell => prepare_powershell(&script),
    }
}

/// zsh: a generated `ZDOTDIR`.
///
/// zsh reads `.zshenv`, `.zprofile`, `.zshrc`, and `.zlogin` from `ZDOTDIR`, so
/// all four need a shim — miss one and that part of the user's setup silently
/// stops running. Each shim sources the user's real file first.
fn prepare_zsh(dir: &Path, script: &Path) -> Injection {
    let zdotdir = dir.join("zdotdir");
    if let Err(e) = std::fs::create_dir_all(&zdotdir) {
        return Injection::unavailable(format!("Could not create a ZDOTDIR: {e}"));
    }

    // Where the user's own zsh files live right now.
    let user_zdotdir = std::env::var("ZDOTDIR")
        .ok()
        .filter(|s| !s.is_empty())
        .or_else(|| dirs::home_dir().map(|h| h.display().to_string()))
        .unwrap_or_else(|| "$HOME".to_string());

    // `.zshenv` runs first and for every shell, so it is where the original
    // location is recorded for the later files to use.
    let zshenv = r#"# Generated by Tervin. Do not edit; it is rewritten on every launch.
#
# Tervin points ZDOTDIR here so it can load its shell hook without modifying any
# of your files. Your own configuration is sourced below, unchanged and first.

TERVIN_USER_ZDOTDIR="${TERVIN_USER_ZDOTDIR:-$HOME}"

# Your .zshenv, exactly as zsh would have read it.
if [ -f "$TERVIN_USER_ZDOTDIR/.zshenv" ]; then
  ZDOTDIR="$TERVIN_USER_ZDOTDIR" . "$TERVIN_USER_ZDOTDIR/.zshenv"
fi
"#;

    let zprofile = r#"# Generated by Tervin. Do not edit.
if [ -f "$TERVIN_USER_ZDOTDIR/.zprofile" ]; then
  ZDOTDIR="$TERVIN_USER_ZDOTDIR" . "$TERVIN_USER_ZDOTDIR/.zprofile"
fi
"#;

    // `.zshrc` is the interactive one, so the hook goes here — after the user's
    // rc, because the hook appends to PS1 and must see the final prompt.
    let zshrc = format!(
        r#"# Generated by Tervin. Do not edit.

if [ -f "$TERVIN_USER_ZDOTDIR/.zshrc" ]; then
  ZDOTDIR="$TERVIN_USER_ZDOTDIR" . "$TERVIN_USER_ZDOTDIR/.zshrc"
fi

# Restore ZDOTDIR before anything else can observe it, so a later `exec zsh`,
# a prompt framework, or a plugin manager sees your value rather than Tervin's.
ZDOTDIR="$TERVIN_USER_ZDOTDIR"
export ZDOTDIR

# The hook last: it appends a zero-width prompt marker and must run after your
# prompt is final. It is a no-op outside Tervin, and TERVIN_SHELL_INTEGRATION=0
# disables it.
[ -f "{script}" ] && . "{script}"
"#,
        script = script.display()
    );

    let zlogin = r#"# Generated by Tervin. Do not edit.
if [ -f "$TERVIN_USER_ZDOTDIR/.zlogin" ]; then
  ZDOTDIR="$TERVIN_USER_ZDOTDIR" . "$TERVIN_USER_ZDOTDIR/.zlogin"
fi
"#;

    for (name, body) in [
        (".zshenv", zshenv.to_string()),
        (".zprofile", zprofile.to_string()),
        (".zshrc", zshrc),
        (".zlogin", zlogin.to_string()),
    ] {
        if let Err(e) = std::fs::write(zdotdir.join(name), body) {
            return Injection::unavailable(format!("Could not write {name}: {e}"));
        }
    }

    Injection {
        args: Vec::new(),
        env: vec![
            ("ZDOTDIR".to_string(), zdotdir.display().to_string()),
            ("TERVIN_USER_ZDOTDIR".to_string(), user_zdotdir),
        ],
        unavailable: None,
    }
}

/// bash: `--init-file`.
///
/// This replaces the file bash would read for an interactive shell, so the
/// wrapper has to source the user's own rc itself. Both `.bash_profile` and
/// `.bashrc` are considered, in the order bash would.
fn prepare_bash(dir: &Path, script: &Path) -> Injection {
    let wrapper = dir.join("tervin-bash-init.sh");
    let body = format!(
        r#"# Generated by Tervin. Do not edit; it is rewritten on every launch.
#
# Passed to bash with --init-file so Tervin can load its hook without modifying
# any of your files. Your own configuration is sourced first, unchanged.

# bash reads .bash_profile for a login shell and .bashrc otherwise. --init-file
# replaces that, so the same order is reproduced here.
if [ -f "$HOME/.bash_profile" ]; then
  . "$HOME/.bash_profile"
elif [ -f "$HOME/.bash_login" ]; then
  . "$HOME/.bash_login"
elif [ -f "$HOME/.profile" ]; then
  . "$HOME/.profile"
fi

# A .bash_profile commonly sources .bashrc itself; guard against doing it twice.
if [ -z "$TERVIN_BASHRC_SOURCED" ] && [ -f "$HOME/.bashrc" ]; then
  case "$-" in
    *i*) TERVIN_BASHRC_SOURCED=1 . "$HOME/.bashrc" ;;
  esac
fi

# The hook last: it appends a prompt marker and chains PROMPT_COMMAND, so it must
# see your final prompt.
[ -f "{script}" ] && . "{script}"
"#,
        script = script.display()
    );

    if let Err(e) = std::fs::write(&wrapper, body) {
        return Injection::unavailable(format!("Could not write the bash init file: {e}"));
    }

    Injection {
        // `--init-file` only applies to an interactive shell, so `-i` is required
        // for it to be read at all.
        args: vec![
            "--init-file".to_string(),
            wrapper.display().to_string(),
            "-i".to_string(),
        ],
        env: Vec::new(),
        unavailable: None,
    }
}

/// fish: `vendor_conf.d`, its documented extension point.
///
/// No wrapper and no override — fish is explicitly designed for a third party to
/// drop a file into `XDG_DATA_DIRS/fish/vendor_conf.d/`, which is exactly this
/// case. The user's own config is untouched and still runs.
fn prepare_fish(dir: &Path, shell: Shell) -> Injection {
    let vendor = dir.join("fish").join("vendor_conf.d");
    if let Err(e) = std::fs::create_dir_all(&vendor) {
        return Injection::unavailable(format!("Could not create vendor_conf.d: {e}"));
    }
    if let Err(e) = std::fs::write(vendor.join("tervin.fish"), shell.script()) {
        return Injection::unavailable(format!("Could not write the fish hook: {e}"));
    }

    // Prepend rather than replace: dropping the system entries would remove
    // completions and functions the user depends on.
    let existing = std::env::var("XDG_DATA_DIRS").unwrap_or_default();
    let combined = if existing.is_empty() {
        format!("{}:/usr/local/share:/usr/share", dir.display())
    } else {
        format!("{}:{existing}", dir.display())
    };

    Injection {
        args: Vec::new(),
        env: vec![("XDG_DATA_DIRS".to_string(), combined)],
        unavailable: None,
    }
}

/// PowerShell: `-NoExit -Command`, which runs after the profile has loaded.
fn prepare_powershell(script: &Path) -> Injection {
    Injection {
        args: vec![
            "-NoExit".to_string(),
            "-Command".to_string(),
            format!(". '{}'", script.display()),
        ],
        env: Vec::new(),
        unavailable: None,
    }
}

/// Where the generated zsh `ZDOTDIR` lives, for the settings pane to show.
pub fn zdotdir_path(dir: &Path) -> PathBuf {
    dir.join("zdotdir")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn tmp() -> PathBuf {
        let dir = std::env::temp_dir().join(format!("tervin-inject-{}", uuid_like()));
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    fn uuid_like() -> String {
        format!(
            "{}-{:?}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        )
    }

    #[test]
    fn zsh_injection_sets_zdotdir_and_writes_all_four_rc_files() {
        // Missing any one of these silently stops part of the user's setup.
        let dir = tmp();
        let injection = prepare(Shell::Zsh, &dir, InjectionMode::Automatic);
        assert!(injection.is_active());

        let zdotdir = zdotdir_path(&dir);
        for name in [".zshenv", ".zprofile", ".zshrc", ".zlogin"] {
            assert!(zdotdir.join(name).exists(), "{name} was not written");
        }

        let env: std::collections::HashMap<_, _> = injection.env.into_iter().collect();
        assert_eq!(
            env.get("ZDOTDIR").map(String::as_str),
            Some(zdotdir.display().to_string().as_str())
        );
        assert!(env.contains_key("TERVIN_USER_ZDOTDIR"));

        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn zsh_sources_the_users_config_before_the_hook() {
        // Order matters: the hook appends a prompt marker, so it must see the
        // user's final prompt.
        let dir = tmp();
        prepare(Shell::Zsh, &dir, InjectionMode::Automatic);
        let zshrc = std::fs::read_to_string(zdotdir_path(&dir).join(".zshrc")).unwrap();

        let user_at = zshrc
            .find("TERVIN_USER_ZDOTDIR/.zshrc")
            .expect("user rc not sourced");
        let hook_at = zshrc.find("tervin.zsh").expect("hook not sourced");
        assert!(user_at < hook_at, "the hook must load after the user's rc");

        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn zsh_restores_zdotdir_for_anything_that_reads_it_later() {
        // A plugin manager or `exec zsh` must see the user's value, not Tervin's.
        let dir = tmp();
        prepare(Shell::Zsh, &dir, InjectionMode::Automatic);
        let zshrc = std::fs::read_to_string(zdotdir_path(&dir).join(".zshrc")).unwrap();
        assert!(zshrc.contains(r#"ZDOTDIR="$TERVIN_USER_ZDOTDIR""#));
        assert!(zshrc.contains("export ZDOTDIR"));
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn zsh_generated_files_guard_against_a_missing_user_file() {
        // A machine with no .zprofile must not produce an error on every launch.
        let dir = tmp();
        prepare(Shell::Zsh, &dir, InjectionMode::Automatic);
        for name in [".zshenv", ".zprofile", ".zshrc", ".zlogin"] {
            let body = std::fs::read_to_string(zdotdir_path(&dir).join(name)).unwrap();
            assert!(body.contains("[ -f"), "{name} does not check for existence");
        }
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn bash_injection_uses_init_file_and_requires_interactive() {
        // --init-file is ignored unless the shell is interactive.
        let dir = tmp();
        let injection = prepare(Shell::Bash, &dir, InjectionMode::Automatic);
        assert!(injection.is_active());
        assert!(injection.args.iter().any(|a| a == "--init-file"));
        assert!(injection.args.iter().any(|a| a == "-i"));
        assert!(dir.join("tervin-bash-init.sh").exists());
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn bash_wrapper_reproduces_the_shell_startup_order() {
        let dir = tmp();
        prepare(Shell::Bash, &dir, InjectionMode::Automatic);
        let body = std::fs::read_to_string(dir.join("tervin-bash-init.sh")).unwrap();

        let profile = body.find(".bash_profile").expect("no .bash_profile");
        let bashrc = body.find(".bashrc").expect("no .bashrc");
        let hook = body.find("tervin.bash").expect("no hook");
        assert!(profile < bashrc, "profile must come before bashrc");
        assert!(bashrc < hook, "the hook must load last");
        // A .bash_profile that sources .bashrc must not cause a double-source.
        assert!(body.contains("TERVIN_BASHRC_SOURCED"));

        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn fish_uses_its_own_vendor_extension_point() {
        // fish is designed for this, so no wrapper and no override is needed.
        let dir = tmp();
        let injection = prepare(Shell::Fish, &dir, InjectionMode::Automatic);
        assert!(injection.is_active());
        assert!(dir.join("fish/vendor_conf.d/tervin.fish").exists());

        let env: std::collections::HashMap<_, _> = injection.env.into_iter().collect();
        let dirs = env.get("XDG_DATA_DIRS").expect("XDG_DATA_DIRS not set");
        assert!(dirs.starts_with(&dir.display().to_string()));
        // Never replace the system entries: completions and functions live there.
        assert!(dirs.contains("/usr/share") || dirs.contains(':'));

        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn powershell_runs_the_hook_after_the_profile() {
        let dir = tmp();
        let injection = prepare(Shell::PowerShell, &dir, InjectionMode::Automatic);
        assert!(injection.args.iter().any(|a| a == "-NoExit"));
        assert!(injection.args.iter().any(|a| a.contains("tervin.ps1")));
        // -NoProfile would skip the user's profile entirely.
        assert!(!injection.args.iter().any(|a| a == "-NoProfile"));
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn off_mode_injects_nothing() {
        let dir = tmp();
        let injection = prepare(Shell::Zsh, &dir, InjectionMode::Off);
        assert!(!injection.is_active());
        assert!(injection.args.is_empty());
        assert!(injection.env.is_empty());
        // And writes nothing.
        assert!(!zdotdir_path(&dir).exists());
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn injection_never_writes_outside_tervins_own_directory() {
        // The whole promise of this module: no file the user owns is touched.
        let dir = tmp();
        for shell in crate::ALL_SHELLS {
            prepare(shell, &dir, InjectionMode::Automatic);
        }

        // Everything created is inside `dir`.
        let mut count = 0;
        fn walk(path: &Path, count: &mut usize) {
            if let Ok(entries) = std::fs::read_dir(path) {
                for entry in entries.flatten() {
                    *count += 1;
                    if entry.path().is_dir() {
                        walk(&entry.path(), count);
                    }
                }
            }
        }
        walk(&dir, &mut count);
        assert!(count > 0, "nothing was written at all");

        std::fs::remove_dir_all(&dir).ok();
    }
}
