# Generated by .github/workflows/release.yml for v0.1.0. Do not edit:
# change packaging/homebrew/tervin.rb, which this is built from.
# Homebrew cask for Tervin — the template the release workflow fills in.
#
# This repository is its own tap. Homebrew reads casks from `Casks/`, and
# `brew tap <name> <url>` accepts any URL — the `homebrew-` repository prefix is only
# what the one-argument shortcut assumes. So there is no second repository to keep in
# step with this one.
#
# `.github/workflows/release.yml` substitutes the placeholders below and commits the
# result to `Casks/tervin.rb`. **Edit this file, not that one.**
cask "tervin" do
  version "0.1.0"

  # One URL and one checksum, because the build produces one universal DMG
  # (`--target universal-apple-darwin`) rather than a binary per architecture.
  #
  # An earlier version of this cask split on `on_arm`/`on_intel` and pointed at
  # `Tervin_<v>_aarch64.dmg` and `Tervin_<v>_x64.dmg` — filenames that build has never
  # produced. Every `brew install --cask` would have 404'd on the first release.
  #
  # The filename is substituted rather than composed from `version`, because Tauri
  # decides it and guessing it is what caused that bug.
  #
  # `:no_check` is deliberately not used: it would mean Homebrew installs whatever the
  # URL currently serves, which is the one thing a checksum exists to prevent.
  sha256 "11e296e265fd14ad24591f99d32685cc39686182c439ef55bb9b63dad64c5ca8"
  url "https://github.com/QuintinBotes/tervin/releases/download/v#{version}/Tervin_0.1.0_universal.dmg",
      verified: "github.com/QuintinBotes/tervin/"

  name "Tervin"
  desc "Agent-native terminal workspace"
  homepage "https://github.com/QuintinBotes/tervin"

  # Pre-1.0: a minor release may change on-disk formats, so an auto-upgrade should be
  # a deliberate act until the schema settles.
  livecheck do
    url :url
    strategy :github_latest
  end

  # The bundle declares 10.13, but Tervin is only tested on Sonoma and later and its
  # PTY tests run against the tools those versions ship. Claiming the lower bound the
  # linker happens to allow would be claiming support that was never exercised.
  # The symbol form, not `">= :sonoma"`: Homebrew deprecated string comparison here.
  # Verified with `brew info` against a real local tap — both report "macOS >= 14", so
  # the symbol means *at least* that version rather than exactly it.
  depends_on macos: :sonoma

  app "Tervin.app"

  # Everything Tervin writes, so an uninstall actually uninstalls. Listed explicitly
  # rather than with a glob: a wildcard under Application Support has removed more
  # than it should in other casks.
  # Paths verified against a built bundle: the identifier is `dev.tervin.app`, and on
  # macOS Tervin's config and data both live under Application Support because that is
  # what `dirs` returns there — there is no `~/.config/tervin` on this platform.
  zap trash: [
    "~/Library/Application Support/tervin",
    "~/Library/Caches/dev.tervin.app",
    "~/Library/Saved Application State/dev.tervin.app.savedState",
    "~/Library/WebKit/dev.tervin.app",
  ]

  caveats do
    # Said here rather than discovered at first launch. An unsigned build shows a
    # Gatekeeper warning, and pretending otherwise wastes a user's trust.
    <<~EOS
      Tervin injects its shell integration per pane and never modifies your rc files.
      Disable it with TERVIN_SHELL_INTEGRATION=0 or in Settings.

      Tervin is a terminal, not a sandbox. Agents run with your privileges. See
      SECURITY.md for what its permission gates can and cannot enforce.
    EOS
  end
end
