# Generated by .github/workflows/release.yml for v0.1.0. Do not edit:
# change packaging/homebrew/tervin-formula.rb, which this is built from.
# A Homebrew *formula* that builds Tervin from source.
#
# Exists alongside the cask because the two differ in a way that matters on macOS: a
# cask downloads a prebuilt app and Homebrew marks it quarantined, so an unsigned build
# hits Gatekeeper. A formula compiles locally, and a locally produced binary is never
# quarantined — so this route works with no Apple Developer ID and no warning dialog.
#
# The cost is real: a Rust and Node toolchain, and several minutes of compilation. Both
# routes are offered because neither is right for everyone.
class Tervin < Formula
  desc "Agent-native terminal workspace"
  homepage "https://github.com/QuintinBotes/tervin"
  url "https://github.com/QuintinBotes/tervin/archive/refs/tags/v0.1.0.tar.gz"
  sha256 "837efbe8137138fb8f9f5807a13965cf676c94e7803cca3ad3867afbf923c650"
  license "MIT"
  head "https://github.com/QuintinBotes/tervin.git", branch: "main"

  depends_on "node" => :build
  depends_on "rust" => :build
  depends_on :macos

  def install
    system "npm", "ci"
    system "npx", "tauri", "build", "--bundles", "app"

    # The bundle goes to the prefix and is symlinked into the Applications directory,
    # which is how Homebrew expects a formula to ship a .app.
    prefix.install "target/release/bundle/macos/Tervin.app"

    # A CLI shim, so `tervin` on PATH opens the app rather than running the inner
    # Mach-O directly — launching through LaunchServices is what gives the bundle its
    # Info.plist, its icon, and a normal application lifecycle.
    (bin/"tervin").write <<~SH
      #!/bin/sh
      exec open -a "#{prefix}/Tervin.app" --args "$@"
    SH
    chmod 0755, bin/"tervin"
  end

  def caveats
    <<~EOS
      Built from source, so macOS does not quarantine it and there is no Gatekeeper
      warning.

      Tervin injects its shell integration per pane and never modifies your rc files.
      Disable it with TERVIN_SHELL_INTEGRATION=0 or in Settings.

      Tervin is a terminal, not a sandbox. Agents run with your privileges. See
      SECURITY.md for what its permission gates can and cannot enforce.
    EOS
  end

  test do
    # The app cannot be launched headlessly, so this asserts the bundle is well formed
    # and that its executable is the one the shim points at.
    assert_predicate prefix/"Tervin.app/Contents/MacOS/tervin", :executable?
    assert_match "Tervin.app", (bin/"tervin").read
  end
end
