#!/usr/bin/env bash
#
# One-time setup for the distribution channels.
#
# Everything after this is automatic: a `v*` tag builds, releases, publishes to npm, and
# updates the Homebrew tap with checksums computed during that build. This script exists
# because the accounts and repositories cannot be created by a workflow that needs them
# to already exist.
set -euo pipefail

REPO="QuintinBotes/tervin"
TAP="QuintinBotes/homebrew-tervin"

say() { printf '\n\033[1m%s\033[0m\n' "$*"; }
ok()  { printf '  ✓ %s\n' "$*"; }
todo(){ printf '  → %s\n' "$*"; }

command -v gh >/dev/null || {
  echo "This needs the GitHub CLI: brew install gh && gh auth login"
  exit 1
}

say "1. The main repository"
if gh repo view "$REPO" >/dev/null 2>&1; then
  ok "$REPO exists"
else
  todo "creating $REPO"
  gh repo create "$REPO" --public --source=. --remote=origin --push
fi

say "2. The Homebrew tap"
# Homebrew resolves `brew install QuintinBotes/tervin/tervin` to the repository
# `QuintinBotes/homebrew-tervin`. The `homebrew-` prefix is required.
if gh repo view "$TAP" >/dev/null 2>&1; then
  ok "$TAP exists"
else
  todo "creating $TAP"
  tmp="$(mktemp -d)"
  mkdir -p "$tmp/Casks" "$tmp/Formula"
  cat > "$tmp/README.md" <<'MD'
# Homebrew tap for Tervin

```sh
# Build from source — no Gatekeeper prompt, needs a Rust and Node toolchain
brew install --formula QuintinBotes/tervin/tervin

# Prebuilt app — faster, but Homebrew quarantines cask downloads, so macOS will
# ask you to approve it once in System Settings › Privacy & Security
brew install --cask QuintinBotes/tervin/tervin
```

Both files here are generated by Tervin's release workflow. Edit them in
[the main repository](https://github.com/QuintinBotes/tervin/tree/main/packaging/homebrew)
instead — changes made here are overwritten by the next release.
MD
  (cd "$tmp" && git init -q && git add . && git commit -qm "tap skeleton")
  gh repo create "$TAP" --public --source="$tmp" --remote=tap --push
  ok "created $TAP"
fi

say "3. Secrets"
existing="$(gh secret list --repo "$REPO" 2>/dev/null | awk '{print $1}' || true)"
have() { echo "$existing" | grep -qx "$1"; }

if have NPM_TOKEN; then
  ok "NPM_TOKEN set"
else
  todo "NPM_TOKEN — an npm automation token (npmjs.com › Access Tokens › Granular, publish scope)"
  todo "  gh secret set NPM_TOKEN --repo $REPO"
fi

if have TAP_GITHUB_TOKEN; then
  ok "TAP_GITHUB_TOKEN set"
else
  todo "TAP_GITHUB_TOKEN — a PAT with Contents: write on $TAP only"
  todo "  gh secret set TAP_GITHUB_TOKEN --repo $REPO"
fi

# Signing is genuinely optional: npx and the source formula are unaffected by it, and
# the release says plainly when a build is unsigned.
if have APPLE_SIGNING_IDENTITY; then
  ok "Apple signing configured"
else
  todo "Apple signing is NOT configured (optional)"
  todo "  Without it: npx and 'brew install --formula' still open with no prompt."
  todo "  The .dmg and the cask will ask for one-time approval in System Settings."
  todo "  To enable, set: APPLE_CERTIFICATE APPLE_CERTIFICATE_PASSWORD"
  todo "                  APPLE_SIGNING_IDENTITY APPLE_ID APPLE_PASSWORD APPLE_TEAM_ID"
fi

say "4. Releasing"
V="$(sed -n 's/^version = "\(.*\)"/\1/p' Cargo.toml | head -1)"
todo "the workflow requires the tag to match the workspace version, currently ${V}"
todo "  git tag v${V} && git push origin v${V}"
echo
todo "a manual run builds and verifies without publishing:"
todo "  gh workflow run release.yml --repo $REPO"
echo
